"""Make wallet.user one-to-one

Revision ID: 1b66a250e6f2
Revises: 3bbd683f9eeb
Create Date: 2025-05-23 04:06:56.976762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b66a250e6f2'
down_revision = '3bbd683f9eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('trade_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('trade_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
